#######################################
#  Appleseed.Leaves.App
#######################################
version: '2.1'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=rahul.singh@anant.us
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.99.100
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
    ports:
      - 80:80
    volumes:
      - //C/Users/DELL/Docker_proj/wallabag/wallabag_images:/var/www/wallabag/web/assets/images

  db:
    image: mariadb
    command: 
      --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE

    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - //C/Users/DELL/Docker_proj/wallabag/wallabag_mysql:/var/lib/mysql

  redis:
    image: redis:alpine

  awesome_transform:
    image: jagannathbilgi/awesome-transform
    environment:
      - REDIS_IP={{redis|container_ip}}

    volumes:
      - c:\Users\DELL\Docker_proj\wallabag\awesome_share:/var/awesome

    ports:
      - 5000:5000

  redis_aggregate:
    image: jagannathbilgi/redis_aggregate
    environment:
      - REDIS_IP={{redis|container_ip}}

    volumes:
      - c:\Users\DELL\Docker_proj\wallabag\awesome_share:/var/awesome

  cassandra:
    image: cassandra:latest
    volumes:
      - c:\Users\DELL\Docker_proj\wallabag\cassandra-persistence:/var/lib/cassandra:rw


  redis_collect:
    image: jagannathbilgi/redis_collect_new
    environment:
      - CASS_IP={{cassandra:9042}}

  redis_solr:
    image: jagannathbilgi/redis_solr

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 83:80
      
  solr:
     image: solr
     ports: 
       - "8983:8983"
     volumes: 
       - ./mycores:/opt/solr/server/solr/mycores
       - ./myconf:/opt/solr/server/solr/configsets/myconf
     entrypoint:
       - solr-precreate
       - mycore2
       - /opt/solr/server/solr/configsets/myconf
